### ISSUE TITLE
Command helper support Korean language

### ISSUE THREAD

**Issue by AcogKR** [EngineHub/CommandHelper#1174]

**Comment by LadyCailin** [comment]
So I don’t intend on ever changing things like function names, however, I have set up a framework to localize the documentation into different languages on the official website. If you would like to help with this effort, check out https://methodscript.com/docs/3.3.4/Localization.html

If I get a good translation database for one language, I would then integrate that into other things, such as the local documentation via reflect_pull, inside the Visual Studio Code extension, etc. so while I don’t want to translate things like functions names, I do want everything else to be accessible to non English speakers. Let me know if you want to help!
