### ISSUE TITLE
executeas() with not enough arguments leads to an error in core

### ISSUE THREAD

**Issue by Pieter12345** [EngineHub/CommandHelper#1194]
Any number of arguments is allowed in `executeas()`, but the required minimum argument size is never checked and the following line causes a negative array index:
https://github.com/EngineHub/CommandHelper/blob/master/src/main/java/com/laytonsmith/core/functions/DataHandling.java#L2368

**Comment by PseudoKnight** [comment]
Fixed in https://github.com/EngineHub/CommandHelper/commit/309df09d3c965137d7ee3caebaa290506ffcb7d9
