### ISSUE TITLE
NPE on incorrect proc definition with returning type

### ISSUE THREAD

**Issue by KanoAlgiz** [EngineHub/CommandHelper#1203]
in main.ms
`include('test.ms')`
in test.ms
`void _main(){}`

Stacktrace: https://pastebin.com/BEU1TNEW

But, if you write `void _procname(){}` directly in main.ms - no stacktrace, just two compile errors: 
![изображение](https://user-images.githubusercontent.com/11517044/83358605-66410c80-a37d-11ea-9d18-e89737c47e2d.png)

**Comment by Pieter12345** [comment]
Correct syntax for procs with type is:
```
proc void _main() {}
```
Getting a Java stacktrace for invalid syntax is a bug though.

**Comment by KanoAlgiz** [comment]
Yes, I quckly found that I've mistyped, but it felt right to report =)
Btw, `void proc`, not `proc void`

compile error with 'unknown source' looks strange too...

**Comment by Pieter12345** [comment]
It is odd that the term does not have a known Target (unknown source). I've fixed the Java exception from being thrown in my PR, but the CClassType with an unknown target should still get its target properly assigned.
