### ISSUE TITLE
UnsupportedOperationException from include_dir()

### ISSUE THREAD

**Issue by Anatoliy057** [EngineHub/CommandHelper#1219]
If only `include_dir()` is called in the script (no more operations are present), then an UnsupportedOperationException is thrown

https://github.com/EngineHub/CommandHelper/blob/7df115a355507268f9d2448508206e7e346831ac/src/main/java/com/laytonsmith/core/functions/DataHandling.java#L1908

**Comment by LadyCailin** [comment]
Oh weird, that means it's not being optimized out properly.
