### ISSUE TITLE
Thanks Commandhelper

### ISSUE THREAD

**Issue by luigivivian** [EngineHub/CommandHelper#1226]
i started programming with commandhelper, nowadays I'm a full stack web developer, thanks commandhelper.
I learned and developed all programming logic using commandhelper, I am extremely grateful for that, commandhelper made it possible for me to become a developer, this is more than 6 years ago, today I am graduated and improved in mobile and web development.
The beginning of everything was the commandhelper, I did it for fun and today is my job so I just thank

**Comment by Pieter12345** [comment]
That's nice to hear! Feel welcome on the [CommandHelper Discord server](https://discord.gg/Z7jpHed), which is a nice place to talk to other users and developers.

**Comment by LadyCailin** [comment]
This is very heartwarming to hear! I'm glad it had such an impact on you!
