### ISSUE TITLE
Escaping @ in double brackets

### ISSUE THREAD

**Issue by Anatoliy057** [EngineHub/CommandHelper#1229]
In cases **"\\\\@"** and **"\\@"**, the output will be **"@"**

**Comment by LadyCailin** [comment]
`@` is the expected output for `"\@"`, as that's the correct escape sequence for a literal at sign.

**Comment by Pieter12345** [comment]
This is likely an issue in the parser. With one backslash char, `smart_string('\\@')` properly results in `@`, and with two backslash chars, `smart_string('\\\\@')` properly results in `\@`, so the compiler function representing the smart string seems to work properly.
