### ISSUE TITLE
Code in auto_include.ms is executed on every alias usage

### ISSUE THREAD

**Issue by KanoAlgiz** [EngineHub/CommandHelper#1235]
in auto_include.ms:
`console('i want to be executed only on recompile!')`

in aliases.msa
`/test = console('good luck with that')`

code in auto_include will be fired on every /test command usage by any player or from console

**Comment by Pieter12345** [comment]
The `auto_include.ms` file is intended for procedure declarations. If you want code to run only once on recompile, then you'd have to put it in another `.ms` file instead (e.g. `main.ms`). Read the part under `main.ms, auto_include.ms, and aliases.msa` in the [Advanced Guide](https://methodscript.com/docs/3.3.4/Advanced_Guide.html) for a more precise explanation of what each file does.

**Comment by KanoAlgiz** [comment]
Thank you!
But is it required to re-register all procs defined there on every alias usage?

**Comment by Pieter12345** [comment]
Following the intention of how things should work (ignoring some things you could currently do, but are considered bad practise), you'd either define a procedure in a 'normal' `.ms` file before you use it, through an `include()` before you use it, or in an `auto_include.ms` file. If you do not have good reasons to not put it in an `auto_include.ms` file, then it should go in there.
