### ISSUE TITLE
Cannot create a shield without a banner

### ISSUE THREAD

**Issue by LeigerGaming** [EngineHub/CommandHelper#1276]
Run this command:
```java
/test_shield = >>>
  @normal_shield = array(name: 'SHIELD', meta: array());
  add_to_inventory(puuid(), @normal_shield);

  @white_shield = array(name: 'SHIELD', meta: array(basecolor: 'WHITE'));
  add_to_inventory(puuid(), @white_shield);
<<<
```
Both shields have a white banner, but the first one should not.

Reported by AAAA#6692 in Discord.

@PseudoKnight wrote:
> I understand why it's happening. A complete solution is not apparent yet.
> If I haven't made a choice by tomorrow I'll write something up.

I believe he is actively looking into a fix for this issue.

**Comment by PseudoKnight** [comment]
Technically you can create a shield without a banner by not applying any meta. A special case will have to be made for shields when processing BlockStateMeta.
