### ISSUE TITLE
[Feature request] Add get_world_autosave(string) and set_world_autosave(string, boolean)

### ISSUE THREAD

**Issue by Pieter12345** [EngineHub/CommandHelper#1288]
# Feature request
I would like to have the following Bukkit API functions exposed to CH:
- https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#isAutoSave() as `get_world_autosave(string)`
- https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#setAutoSave(boolean) as `set_world_autosave(string, boolean)`

# Feature applications
Example applications where these functions would be useful:
- Running custom autosaves while respecting autosave settings.
- Toggling autosave temporarily off while making (automated) backups of world files.

**Comment by Adityaintel** [comment]
I'll work on it.

**Comment by PseudoKnight** [comment]
Added in 3db829087e7df46d8989635074731090b8e2bf64
