### ISSUE TITLE
[Feature request] colorize() to support hex colors

### ISSUE THREAD

**Issue by malonnnn** [EngineHub/CommandHelper#1357]
Would love to be able to do `colorize('#87CEEBFlight &8Master')`

**Comment by Pieter12345** [comment]
Appears that `colorize(&#11223344)` does work, but is not documented. That reforms the feature request to updating the `colorize()` documentation.

![afbeelding](https://user-images.githubusercontent.com/9693840/230242064-65874b09-4510-43d9-a2ed-4c980b4258fb.png)

**Comment by malonnnn** [comment]
The issue I'm having...

from a YML file, I have:

`niceName: '&#FF00BBTest &1T&2e&3s&4t &#888888Test'`

Then I read it in:

```
@char = read('./rpgClasses/'.@class)
@char = yml_decode(@char)
```

Then I print it:

`ptellraw(@player, array(array(text: colorize(@char['niceName']))))`

But it looks like:

https://i.imgur.com/VitIm5Y.png

The first word is a completely wrong color, and the 3rd word looks more like DARK_GRAY on my screenshot, and more like GRAY on yours.

**Comment by PseudoKnight** [comment]
Oh, that's because you're using ptellraw(), which doesn't really support hex colors in the text value. (it seems to be using the last color code from the hex code, in this case: 'B') Use text component colors there instead.

**Comment by PseudoKnight** [comment]
e.g. `ptellraw(@player, array(array(color: '#FF00BB', text: 'Test')))`

**Comment by PseudoKnight** [comment]
Multiple colors would require multiple text components.

`ptellraw(@player, array(array(color: '#FF0000', text: 'T'), array(color: '#BB0000, text: 'e'), array(color: '#880000', text: 's'), array(color: '#330000', text: 't')))`

This is just the json text format mojang uses. https://minecraft.fandom.com/wiki/Raw_JSON_text_format

**Comment by malonnnn** [comment]
So are you saying I can't have a feature request to simplify this process?

Like how would I store a complicated colored name in a yaml file? I mean since ptellraw supports standard color codes already, I feel it should also support hex.

**Comment by PseudoKnight** [comment]
Yes. It supports all the most common features that you'd likely use. There's pros and cons to each approach, but I think minimessage would fit your use case quite well, if you like the format.

**Comment by LadyCailin** [comment]
We should still update the docs for colorize to indicate that they support hex colors.
